# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bowrna.github.io/
baseurl: 
title: Bowrna Prabhakaran
author: Bowrna Prabhakaran
description: Personal blog and resume
avatar: Bowrna.jpeg
email: mailbowrna@gmail.com
github: Bowrna # username
twitter: BowrnaPrabhu
linkedin: bowrna-prabhakaran
stackoverflow: users/3101838/bowrna  #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
